import os
import re
import math
import uuid
import sqlite3
import json
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])

DB_PATH = "provenance.db"


# ---------------------------------------------------------------------------
# Database setup
# ---------------------------------------------------------------------------

def init_db():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS audit_log (
                content_id      TEXT PRIMARY KEY,
                creator_id      TEXT NOT NULL,
                timestamp       TEXT NOT NULL,
                text_snippet    TEXT NOT NULL,
                attribution     TEXT NOT NULL,
                confidence      REAL NOT NULL,
                llm_score       REAL NOT NULL,
                stylo_score     REAL,
                status          TEXT NOT NULL DEFAULT 'classified',
                appeal_reasoning TEXT,
                appeal_timestamp TEXT,
                label           TEXT NOT NULL
            )
        """)
        conn.commit()


def write_log_entry(entry: dict):
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            INSERT INTO audit_log (
                content_id, creator_id, timestamp, text_snippet,
                attribution, confidence, llm_score, stylo_score,
                status, label
            ) VALUES (
                :content_id, :creator_id, :timestamp, :text_snippet,
                :attribution, :confidence, :llm_score, :stylo_score,
                :status, :label
            )
        """, entry)
        conn.commit()


def get_log(limit: int = 50) -> list:
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM audit_log ORDER BY timestamp DESC LIMIT ?", (limit,)
        ).fetchall()
    return [dict(r) for r in rows]


def get_entry(content_id: str) -> dict | None:
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            "SELECT * FROM audit_log WHERE content_id = ?", (content_id,)
        ).fetchone()
    return dict(row) if row else None


def update_appeal(content_id: str, reasoning: str, ts: str):
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            UPDATE audit_log
               SET status = 'under_review',
                   appeal_reasoning = ?,
                   appeal_timestamp = ?
             WHERE content_id = ?
        """, (reasoning, ts, content_id))
        conn.commit()


# ---------------------------------------------------------------------------
# Signal 1: LLM classifier (Groq)
# ---------------------------------------------------------------------------

LLM_PROMPT = """You are an AI content detection assistant. Analyze the text below and estimate the probability that it was generated by an AI language model (as opposed to being written by a human).

Return ONLY valid JSON in this exact format — no explanation, no markdown:
{{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

Where:
- 1.0 = almost certainly AI-generated
- 0.0 = almost certainly human-written
- 0.5 = genuinely uncertain (use this when you truly cannot tell, not as a default)

Consider these markers:
- Uniformly structured sentences, balanced hedging language, generic phrasing, smooth transitions → higher probability
- Irregular sentence rhythm, personal voice, typos, emotional register shifts, idiosyncratic word choices → lower probability

Text to analyze:
\"\"\"
{text}
\"\"\""""


def classify_with_llm(text: str) -> tuple[float, str]:
    """Return (ai_probability 0-1, reasoning string)."""
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": LLM_PROMPT.format(text=text)}],
        temperature=0.1,
        max_tokens=150,
    )
    raw = response.choices[0].message.content.strip()
    # strip markdown code fences if model adds them
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    data = json.loads(raw)
    score = float(data["ai_probability"])
    score = max(0.0, min(1.0, score))
    return score, data.get("reasoning", "")


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics (pure Python)
# ---------------------------------------------------------------------------

def _split_sentences(text: str) -> list[str]:
    """Split on sentence-ending punctuation; filter empties."""
    parts = re.split(r'(?<=[.!?])\s+', text.strip())
    return [p for p in parts if p.strip()]


def _word_count(text: str) -> int:
    return len(re.findall(r"\b\w+\b", text))


def analyze_stylometrics(text: str) -> dict:
    """
    Return a dict with three sub-scores (0–1, higher = more AI-like)
    and a combined stylo_score.

    Sub-metrics per spec:
      1. sentence_length_variance_score — low variance → AI
      2. ttr_score                      — TTR near 0.65 → AI
      3. punctuation_density_score      — low density  → AI
    """
    words = re.findall(r"\b\w+\b", text.lower())
    total_words = len(words)
    total_chars = len(text)

    # --- 1. Sentence length variance ---
    sentences = _split_sentences(text)
    if len(sentences) >= 2:
        sent_lengths = [_word_count(s) for s in sentences]
        mean_len = sum(sent_lengths) / len(sent_lengths)
        variance = sum((l - mean_len) ** 2 for l in sent_lengths) / len(sent_lengths)
        stddev = math.sqrt(variance)
        # stddev 0 → score 1.0 (perfectly uniform = AI)
        # stddev 15+ → score 0.0 (very spiky = human)
        variance_score = max(0.0, 1.0 - stddev / 15.0)
    else:
        # single sentence — can't compute variance; treat as neutral
        variance_score = 0.5

    # --- 2. Type-token ratio ---
    if total_words > 0:
        ttr = len(set(words)) / total_words
        # AI-typical range clusters around 0.65; extremes (very low or high) → human
        # Score = how close TTR is to 0.65 (the AI-typical midpoint)
        ttr_score = max(0.0, 1.0 - abs(ttr - 0.65) / 0.35)
    else:
        ttr_score = 0.5
        ttr = 0.0

    # --- 3. Punctuation density ---
    if total_chars > 0:
        punct_chars = len(re.findall(r'[^\w\s]', text))
        punct_density = punct_chars / total_chars
        # AI text: conservative (~0.02–0.04); human text: messier (higher)
        # Higher density → more human → lower AI score
        # Normalize: 0.08+ density → score 0, 0 density → score 1
        punct_score = max(0.0, 1.0 - punct_density / 0.08)
    else:
        punct_score = 0.5
        punct_density = 0.0

    stylo_score = round((variance_score + ttr_score + punct_score) / 3, 4)

    return {
        "stylo_score": stylo_score,
        "variance_score": round(variance_score, 4),
        "ttr_score": round(ttr_score, 4),
        "punct_score": round(punct_score, 4),
        "ttr": round(ttr, 4) if total_words > 0 else 0.0,
        "punct_density": round(punct_density, 4) if total_chars > 0 else 0.0,
        "sentence_count": len(sentences),
        "word_count": total_words,
    }


# ---------------------------------------------------------------------------
# Confidence scoring & label
# ---------------------------------------------------------------------------

def compute_confidence(llm_score: float, stylo_score: float | None, word_count: int = 100) -> float:
    if stylo_score is None:
        return round(llm_score, 4)
    # For short texts (< 50 words) stylometrics is unreliable — reduce its weight
    if word_count < 50:
        llm_w, stylo_w = 0.9, 0.1
    else:
        llm_w, stylo_w = 0.6, 0.4
    return round(llm_w * llm_score + stylo_w * stylo_score, 4)


def attribution_from_confidence(confidence: float) -> str:
    if confidence >= 0.70:
        return "likely_ai"
    if confidence >= 0.40:
        return "uncertain"
    return "likely_human"


def generate_label(confidence: float) -> str:
    pct = round(confidence * 100)
    if confidence >= 0.70:
        return (
            f"AI-Assisted Content — Our system found strong signals that this content "
            f"may have been generated with AI assistance (confidence: {pct}%). "
            f"This label reflects an automated assessment, not a definitive determination. "
            f"The creator can contest this classification through the appeal process."
        )
    if confidence >= 0.40:
        return (
            f"Origin Unclear — Our system couldn't confidently determine whether this "
            f"content was written by a human or generated with AI assistance "
            f"(confidence: {pct}%). Treat this content as you would any unverified post."
        )
    return (
        f"Likely Human-Written — Our system found no strong signals of AI generation "
        f"in this content (confidence of AI: {pct}%). This is an automated assessment "
        f"and does not constitute a guarantee of human authorship."
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    body = request.get_json(silent=True)
    if not body or not body.get("text") or not body.get("creator_id"):
        return jsonify({"error": "Both 'text' and 'creator_id' are required."}), 400

    text = body["text"].strip()
    creator_id = body["creator_id"].strip()

    if len(text) < 10:
        return jsonify({"error": "Text is too short to analyze."}), 400

    llm_score, llm_reasoning = classify_with_llm(text)
    stylo_result = analyze_stylometrics(text)
    stylo_score = stylo_result["stylo_score"]
    word_count = stylo_result["word_count"]

    confidence = compute_confidence(llm_score, stylo_score, word_count)
    attribution = attribution_from_confidence(confidence)
    label = generate_label(confidence)
    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    write_log_entry({
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "text_snippet": text[:200],
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified",
        "label": label,
    })

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "llm_reasoning": llm_reasoning,
        "stylo_score": stylo_score,
        "stylo_detail": stylo_result,
        "label": label,
        "timestamp": timestamp,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    body = request.get_json(silent=True)
    if not body or not body.get("content_id") or not body.get("creator_reasoning"):
        return jsonify({"error": "Both 'content_id' and 'creator_reasoning' are required."}), 400

    content_id = body["content_id"].strip()
    reasoning = body["creator_reasoning"].strip()

    if not reasoning:
        return jsonify({"error": "'creator_reasoning' cannot be empty."}), 400

    entry = get_entry(content_id)
    if not entry:
        return jsonify({"error": f"No submission found with content_id '{content_id}'."}), 404

    if entry["status"] == "under_review":
        return jsonify({"error": "An appeal is already under review for this submission."}), 409

    ts = datetime.now(timezone.utc).isoformat()
    update_appeal(content_id, reasoning, ts)

    return jsonify({
        "status": "received",
        "content_id": content_id,
        "message": "Your appeal has been logged and will be reviewed.",
        "appeal_timestamp": ts,
    })


@app.route("/log", methods=["GET"])
def log():
    entries = get_log()
    return jsonify({"count": len(entries), "entries": entries})


# ---------------------------------------------------------------------------

if __name__ == "__main__":
    init_db()
    app.run(debug=True)
